### ISSUE TITLE
Missing `aziot-tpmd` for key 'endpoints` when trying to launch identity service

### ISSUE THREAD

**Issue by Haishi2016** [Azure/iot-identity-service#131]
The [doc](https://azure.github.io/iot-identity-service/dev/running/aziot-identityd.html) doesn't mention this field. What should be configured there?

**Comment by daprilik** [comment]
The docs are still in-flux due to the rapid pace of pre-release development.

For your particular question, the `[endpoints]` field of the config file is only used in debug builds, and allows developers to optionally use a different socket path when doing local development. End-users should not use the `[endpoints]` field, as it will simply be ignored.

**Comment by daprilik** [comment]
(will leave issue open until documentation is updated/stabilized)
