### ISSUE TITLE
Buffering issues in log_msg() of tpm/aziot-tpm-sys/azure-iot-hsm-c

### ISSUE THREAD

**Issue by theKidOfArcrania** [Azure/iot-identity-service#233]
Hi. Whenever a message (error/info/dbg) gets [logged in the azure-iot-hsm-c library](https://github.com/Azure/iot-identity-service/blob/main/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_log.c#L39) it uses the `printf` function, which if stdout is set to fully buffered (which would be the case when stdout/stderr gets piped to syslog), the individual log entries do not get written out until it fills up the buffer (which would not be optimal in the case of logging messages and expecting it to be immediately written to a log file/syslog).

A few possible fixes might include, either using `fprintf(stderr, ...)` instead (which I believe is usually always unbuffered), or invoking `fflush(stdout);` after the printf, in order to ensure the log entry gets written out immediately.

**Comment by arsing** [comment]
Yes, it's been on the back of everyone's minds to fix this since back when this code belonged in the iotedge repo. We realized the problem when we saw that the hsm-c logs were always printed in one big dump at the end when the process exited.

And yes, the fix should be to write them to stderr because that's where logs out to go, not to flush stdout.

**Comment by arsing** [comment]
#338 fixes part of the logs to go to stderr, but logs from within the C SDK still go to stdout and are out of our control.

**Comment by arsing** [comment]
The C SDK is no longer used as of 143cdf79be08e7069a6a0b17b38f33469c291b1e
