### ISSUE TITLE
Decrypt not supported for AZIOT_KEYS_ENCRYPT_MECHANISM_RSA_PKCS1

### ISSUE THREAD

**Issue by vslepakov** [Azure/iot-identity-service#311]
It seems that [decrypt](https://github.com/Azure/iot-identity-service/blob/febb3e740fa4aef4f84d9b3042ca426a7d2b8cf2/key/aziot-keyd/src/lib.rs#L419) does not support RSA-PKCS1 (AZIOT_KEYS_ENCRYPT_MECHANISM_RSA_PKCS1)

while encrypt does: https://github.com/Azure/iot-identity-service/blob/febb3e740fa4aef4f84d9b3042ca426a7d2b8cf2/key/aziot-keyd/src/lib.rs#L354 

what is the rationale behind this? I am not able to decrypt what I encrypted or do I miss something?

Thanks
Vitaliy

**Comment by arsing** [comment]
RSA-PKCS1 was wired in as a bare minimum to get TLS using openssl through the openssl engine working. So encryption is needed because it's how signing works with RSA, but decryption is not because openssl does it itself using the pubkey that it already got by [querying the pubkey parameters](https://azure.github.io/iot-identity-service/api/keys-service.html#get-parameter-of-asymmetric-key-pair) when it loaded the key.

**Comment by vslepakov** [comment]
Thanks @arsing.

By 

> but decryption is not because openssl does it itself using the pubkey

you mean that openssl basically can verify a signature using the public key that it's already got, right?

Also wouldn't it make more sense to expose this RSA-PKCS1 encrypt operation through the [sign](https://azure.github.io/iot-identity-service/api/keys-service.html#sign) api?
Right now the documentation suggests that [decrypt](https://azure.github.io/iot-identity-service/api/keys-service.html#decrypt) should actually work with both RSA-PKCS1 and RSA-NO-PADDING which is misleading and one gets _"mechanism cannot be used with this key type"_ trying do do that.

Thanks

**Comment by arsing** [comment]
>you mean that openssl basically can verify a signature using the public key that it's already got, right?

Correct.

>Also wouldn't it make more sense to expose this RSA-PKCS1 encrypt operation through the sign api?

The code path inside openssl and the openssl engine is [the encryption-with-private-key code path.](https://github.com/Azure/iot-identity-service/blob/94f95a1f52c836b29cc9edba8a9a19a0e0b22e95/key/aziot-key-openssl-engine/src/rsa.rs#L58) It's just how RSA works. So I figured it would be appropriate to not pretend that it's something more than what it actually is. Compare with ECDSA that is actually [a signing operation](https://github.com/Azure/iot-identity-service/blob/94f95a1f52c836b29cc9edba8a9a19a0e0b22e95/key/aziot-key-openssl-engine/src/ec_key.rs#L66) so that's wired in through the sign API.

>Right now the documentation suggests that decrypt should actually work with both RSA-PKCS1 and RSA-NO-PADDING which is misleading and one gets "mechanism cannot be used with this key type" trying do do that.

Yes, that should be fixed.

**Comment by vslepakov** [comment]
Ok, got it thanks! I'll just leave the issue open for now and we can close it as soon as the documentation is updated (saw you added the tag).
