### ISSUE TITLE
Getting device key handle when using DPS + TPM attestation

### ISSUE THREAD

**Issue by ElD4n1** [Azure/iot-identity-service#397]
Hi, I am using the identity service version 1.2.6 in conjunction with a TPM 2.0 module and set up DPS TPM attestation.
The device is provisioned successfully and assigned to the configured IoT Hub.
Now I want to get a device connection string for our application to connect to the IoT Hub, but the response from the identityd socket doesn't contain a key handle.

Is it possible to use TPM authentication and then retrieve a SAS key handle for the device identity?

Below is the configuration I am using:

/etc/aziot/config.toml
```
## DPS provisioning with TPM
[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net/"
id_scope = "<our id scope>"

[provisioning.attestation]
method = "tpm"
registration_id = "<my registration id>"
```

/etc/aziot/identityd/config.d/device.toml
```
[[principal]]
uid = 0
name = "somename"
idtype = ["device"]
```

Then I use curl as the root user:
`curl --unix-socket '/run/aziot/identityd.sock' 'http://identityd.sock/identities/identity?api-version=2020-09-01'`
The response is:
`{"type":"aziot","spec":{"hubName":"<the assigned hub>","gatewayHost":"<the assigned hub>","deviceId":"<the device id>","auth":{"type":"tpm"}}}`
What I expected: get a key handle for the device identity.

When I use "module" as idtype instead of "device", then a SAS key handle is returned as expected, but I would prefer using the device identity directly.

**Comment by arsing** [comment]
>but the response from the identityd socket doesn't contain a key handle.

Yes, DPS-TPM provisioning uses tpmd for the provisioning key instead of keyd since the management of that key is TPM-specific, so there is no concept of a key handle, so the get-device-identity API does not return one.

>When I use "module" as idtype instead of "device", then a SAS key handle is returned as expected, but I would prefer using the device identity directly.

A module identity is what I was going to tell you to use, since that is what we recommend in general. Why do you prefer to use the device identity?

---

Alternatively you can use DPS-symmkey or DPS-X509 provisioning with keyd configured to use tpm2-pkcs11, in which case the credential is still protected by the TPM but is accessed via PKCS#11 in the keyd.

**Comment by ElD4n1** [comment]
Ok I understand, I mainly wanted to ask if it was possible to use the device identity because we only have a single application on our device and our backend is currently designed to call direct methods on the device identity.

Then the solution will be to switch to a module identity, the backend changes seem to be small enough for that.

Thanks for the hints!
